version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace
    command: sleep infinity  # 保持容器运行，等待用户执行命令
    working_dir: /workspace
    environment:
      - GOPATH=/go
    networks:
      - devnetwork
    depends_on:
      - db
      - minio  # 添加 MinIO 服务依赖

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"  # 将 PostgreSQL 端口映射到本地机器
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - devnetwork

  minio:
    image: minio/minio:latest
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    ports:
      - "9000:9000" # api 端口
      - "9001:9001" # 控制台端口
    command: server --console-address ':9001' /data  #指定容器中的目录 /data
    volumes:
      - minio-data:/data
    networks:
      - devnetwork

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
    networks:
      - devnetwork
  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - devnetwork

networks:
  devnetwork:
    driver: bridge

volumes:
  postgres-data:
  minio-data:
